-- Insert sample car data
INSERT INTO public.cars (name, brand, model, year, price, fuel_type, car_type, mileage, transmission, image_url, features, description) VALUES
('Toyota Camry 2024', 'Toyota', 'Camry', 2024, 25000, 'petrol', 'sedan', 32, 'automatic', '/placeholder.svg?height=200&width=300', ARRAY['Bluetooth', 'Backup Camera', 'Lane Assist'], 'Reliable mid-size sedan with excellent fuel economy'),
('Honda CR-V 2024', 'Honda', 'CR-V', 2024, 28000, 'petrol', 'suv', 28, 'automatic', '/placeholder.svg?height=200&width=300', ARRAY['AWD', 'Sunroof', 'Apple CarPlay'], 'Spacious and practical compact SUV'),
('Tesla Model 3', 'Tesla', 'Model 3', 2024, 35000, 'electric', 'sedan', 120, 'automatic', '/placeholder.svg?height=200&width=300', ARRAY['Autopilot', 'Supercharging', 'Premium Audio'], 'Premium electric sedan with cutting-edge technology'),
('BMW X3', 'BMW', 'X3', 2024, 45000, 'petrol', 'suv', 25, 'automatic', '/placeholder.svg?height=200&width=300', ARRAY['Leather Seats', 'Navigation', 'Premium Sound'], 'Luxury compact SUV with sporty performance'),
('Volkswagen Golf', 'Volkswagen', 'Golf', 2024, 22000, 'petrol', 'hatchback', 30, 'manual', '/placeholder.svg?height=200&width=300', ARRAY['Sport Mode', 'Digital Cockpit', 'Parking Sensors'], 'Compact hatchback with European styling'),
('Ford Mustang', 'Ford', 'Mustang', 2024, 32000, 'petrol', 'coupe', 20, 'manual', '/placeholder.svg?height=200&width=300', ARRAY['V8 Engine', 'Sport Suspension', 'Performance Tires'], 'Iconic American muscle car'),
('Toyota Prius', 'Toyota', 'Prius', 2024, 27000, 'hybrid', 'hatchback', 50, 'automatic', '/placeholder.svg?height=200&width=300', ARRAY['Hybrid System', 'Eco Mode', 'Solar Roof'], 'Most fuel-efficient hybrid vehicle'),
('Audi A4', 'Audi', 'A4', 2024, 38000, 'petrol', 'sedan', 27, 'automatic', '/placeholder.svg?height=200&width=300', ARRAY['Quattro AWD', 'Virtual Cockpit', 'Bang & Olufsen'], 'Premium German sedan with advanced technology'),
('Jeep Wrangler', 'Jeep', 'Wrangler', 2024, 33000, 'petrol', 'suv', 22, 'manual', '/placeholder.svg?height=200&width=300', ARRAY['4WD', 'Removable Doors', 'Rock Rails'], 'Ultimate off-road adventure vehicle'),
('Nissan Leaf', 'Nissan', 'Leaf', 2024, 30000, 'electric', 'hatchback', 100, 'automatic', '/placeholder.svg?height=200&width=300', ARRAY['ProPILOT', 'e-Pedal', 'NissanConnect'], 'Affordable electric vehicle for daily commuting'),
('Mercedes C-Class', 'Mercedes-Benz', 'C-Class', 2024, 42000, 'petrol', 'sedan', 26, 'automatic', '/placeholder.svg?height=200&width=300', ARRAY['MBUX', 'Air Suspension', 'Burmester Audio'], 'Luxury sedan with sophisticated design'),
('Subaru Outback', 'Subaru', 'Outback', 2024, 29000, 'petrol', 'wagon', 29, 'automatic', '/placeholder.svg?height=200&width=300', ARRAY['Symmetrical AWD', 'EyeSight Safety', 'Roof Rails'], 'Versatile wagon built for adventure'),
('Hyundai Elantra', 'Hyundai', 'Elantra', 2024, 21000, 'petrol', 'sedan', 33, 'automatic', '/placeholder.svg?height=200&width=300', ARRAY['SmartSense', 'Wireless Charging', 'Heated Seats'], 'Affordable sedan with premium features'),
('Mazda CX-5', 'Mazda', 'CX-5', 2024, 27500, 'petrol', 'suv', 26, 'automatic', '/placeholder.svg?height=200&width=300', ARRAY['SKYACTIV', 'Bose Audio', 'i-ACTIVSENSE'], 'Stylish SUV with engaging driving dynamics'),
('Chevrolet Corvette', 'Chevrolet', 'Corvette', 2024, 65000, 'petrol', 'coupe', 18, 'automatic', '/placeholder.svg?height=200&width=300', ARRAY['Mid-Engine', 'Performance Data Recorder', 'Magnetic Ride'], 'American supercar with track-ready performance');
